# Xavier Bresson, 2023
# conda env create -f environment.yml
# conda activate gnn_course
# note: took 5min to solve the env

name: gnn_course


channels:
  
  - conda-forge # numpy/scipy etc
  - pytorch # DL
  - dglteam # GNN
  - pyg # GNN

dependencies:

  # basic
  - python=3.8
  - numpy
  - mkl
  - jupyter
  - ipython
  - matplotlib
  - scipy
  - networkx==2.3
  - scikit-learn
  - pandas
  - seaborn

  # non-DL
  - pymetis
  - python-louvain

  # DL
  - pytorch # DL
  - torchvision # CV 
  - dgl # DGL
  - pyg # PyG
