# Xavier Bresson
# conda env create -f environment.yml
# conda activate gnn_course
# note: It took 10 min to install the environment

name: gnn_course
channels:
  - pypi # pip
  - conda-forge # numpy/scipy etc
  - pytorch # DL
  - defaults
dependencies:
  # basic
  - python=3.8
  - numpy=1.24
  - jupyter=1.0
  - ipython=8.12
  - matplotlib=3.7
  - scipy=1.10.1
  - networkx=3.1
  - pip=24.2
  - pandas=2.0
  - seaborn=0.13
  # graph
  - pymetis=2023.1
  - python-louvain=0.16
  # deep learning
  - pytorch=2.1.2 # DL
  - torchvision=0.16 # CV 
  - pip: # critical : a double indentation is required to install pip packages below !
      - plotly==5.22.0 # interactive 3d visualization
      - scikit-learn==1.3.2 # tsne
      - umap-learn==0.5.6 # data visualization
      - dgl==2.0.0 -f https://data.dgl.ai/wheels/repo.html # gnn / DGL
      - torch_geometric==2.5.1 # gnn / PyG

